Update patch set 1
Sadly this change seems to break the MacOS build, possibly because of
some differences in dirent.h

external/oprofile/libop/op_alloc_counter.c: In function
'op_get_counter_mask':
external/oprofile/libop/op_alloc_counter.c:170: warning: implicit
declaration of function 'scandir'
external/oprofile/libop/op_alloc_counter.c:170: error: 'alphasort'
undeclared (first use in this function)
external/oprofile/libop/op_alloc_counter.c:170: error: (Each undeclared
identifier is reported only once
external/oprofile/libop/op_alloc_counter.c:170: error: for each function
it appears in.)
make: ***
[out/target/product/generic/obj/STATIC_LIBRARIES/libop_intermediates/op_alloc_counter.o]
Error 1

Patch-set: 1